export const lightTheme = {
  token: {
    colorSuccess: "#9eea79",
    colorWarning: "#f5cb76",
    colorError: "#fa6265",
    sizeUnit: 3,
    borderRadius: 3,
    wireframe: true,
    sizeStep: 4,
    colorBgContainer: "#ffffff",
    colorBgLayout: "#f9f9f5",
    colorTextBase: "#252525",
    colorPrimary: "#292929",
    colorInfo: "#292929",
    colorLink: "#67a6ff",
  },
};

export const darkTheme = {
  token: {
    colorSuccess: "#9eea79",
    colorWarning: "#f5cb76",
    colorError: "#fa6265",
    sizeUnit: 3,
    borderRadius: 3,
    wireframe: true,
    sizeStep: 4,
    colorBgContainer: "#292826",
    colorBgLayout: "#33322f",
    colorTextBase: "#f4f4f4",
    colorLink: "#67a6ff",
    colorBgBase: "#282828",
    colorBgElevated: "#1b1b1b",
    colorBgSpotlight: "#ffffff",
    colorFill: "#ffe9c63f",
    colorTextQuaternary: "#fff4e568",
    colorTextTertiary: "#ffffff8e",
    colorText: "#ffffffd9",
    colorBgMask: "#1f1e1dc2",
    colorPrimary: "#c9baa0",
    colorInfo: "#c9c9c9",
  },
  // algorithm: ["dark"],
};
